services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kua-frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kua-backend
    restart: always
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
      - backend-net
    
  dynamodb:
    image: amazon/dynamodb-local
    container_name: kua-dynamodb
    ports:
      - "8000:8000"
    networks:
      - backend-net

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb
    networks:
      - backend-net

networks:
  app-network:
  backend-net: