AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ExpressLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/server.handler
      Runtime: nodejs18.x
      Timeout: 10
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
